### ISSUE TITLE
New screen colors

### ISSUE THREAD

**Issue by serrq** [elastic-rock/Candle#1]
It would be useful if one can decide what color Candle can show.
With preset buttons for quickly recall the favorite ones.

**Comment by elastic-rock** [comment]
What would be the advantage of having the option to choose a different colour? Can you elaborate?

**Comment by elastic-rock** [comment]
Similarly to what I wrote in #2, I have only considered the app to be used as a torch that does not shine as much as the built in torch does. Can you maybe provide another app as an example that fulfils your use case?

**Comment by rhorbas** [comment]
I have a headlamp with a red bulb, so the light does not blind you. Was actually just looking for such a setting in the app.

**Comment by elastic-rock** [comment]
The UI will have have to be adapted in order to see its different elements in contrast with the background that is going to be set by the user, but work is going to be made.
