### ISSUE TITLE
Lockscreen Shortcut

### ISSUE THREAD

**Issue by user44000** [elastic-rock/Candle#10]
Can you add support for setting this app as a shortcut on the lockscreen? This feature is available in LineageOS 20 which is based on Android 13. I'm not sure if it's possible for apps to add custom shortcuts or if this is available in stock Android.
![Screenshot_20240527-004952_Wallpaper   style_1](https://github.com/elastic-rock/Candle/assets/138707369/8a4f8162-815b-4886-bb8a-3166b8169240)

**Comment by elastic-rock** [comment]
Android unfortunately doesn't provide a public API for apps to create custom lockscreen shortcuts. You can, however, use the quick settings tile as an alternative. If such an API becomes available, I will definitely add the feature but for now, it is not possible.
