### ISSUE TITLE
Screen not locking after timeout

### ISSUE THREAD

**Issue by trudnorx** [elastic-rock/Candle#11]
I'm glad that an option was added to allow the screen to time out.
But after the screen turns off, there's no lockscreen when you turn the screen back on.
Other apps don't have this problem, I'm assuming it's due to something this app does.
This is bad for security, so please either always lock the screen or make it another option.
It's inconvenient to have to return to the phone to lock it for my use case.

**Comment by elastic-rock** [comment]
This is not a bug, this is a feature. 🙂For clarification, the device gets locked but the app is permitted to be used even when the device is locked. Normally when you try and exit the app you will get to the lock screen (if that is not the case, there is a serious problem whith your OS or custom ROM).

But regardless of that, I have added the option to turn this behaviour off in the latest release.
