### ISSUE TITLE
Persistent Quick Settings Popup

### ISSUE THREAD

**Issue by ZmaZes** [elastic-rock/Candle#16]
Every time I close the app and reopen it, the app asks me to add a tile to my Quick Settings. I appreciate the tile, but I open the app a different way and don't need the tile, and I wish it would stop asking me to add it. I think it makes more sense for it to ask once the first time you ever open the app, and then possibly a button in settings to add it for user discovery.
Also couldn't figure out how to add a tag to this issue, sorry!

**Comment by ZmaZes** [comment]
Okay! Thanks for looking into it.
The main reason I don't use it is because it doesn't work on the lock screen even when allow on lockscreen is enabled (you have to put in the password). I use a different quick settings tile that runs a script to open the app even when locked.
Let me know if I should make a separate issue for that as a feature request.

**Comment by elastic-rock** [comment]
The device doesn't have to be unlocked when opening the app from the tile but only on Android 13 and below. In Android 14, Google slightly changed the API and at the time, broke the behaviour. I haven't tested it since so I will have a look on that as well (no need to open issue).

Thanks.

**Comment by ZmaZes** [comment]
Okay, cool!

**Comment by ZmaZes** [comment]
Just tested it on my old phone (Android 11) and yep, it works there without unlocking!
I can imagine it gets annoying if they keep changing things around version after version…

**Comment by elastic-rock** [comment]
I will close this issue and recreate one for the unlocking as it will probably take a long time to fix
