### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [elastic-rock/Candle#17]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7784196148#L2071

diff log: [candle12.log](https://github.com/user-attachments/files/16942889/candle12.log)

as a test could you build 1.6.1 with https://github.com/elastic-rock/Candle/blob/v1.6.1/app/build.gradle.kts#L29-L30 set to `false` and attach the APK here?

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/fac9fae79807c678f98a44e80f51ee63959a37b2

**Comment by elastic-rock** [comment]
[com.elasticrock.candle_v1.6.1_MINIFY_DISABLED.apk.zip](https://github.com/user-attachments/files/16944390/app-release.zip)

**Comment by licaon-kter** [comment]
looks like that's not it :( diiflog: [candle12_nomini_norbfix.log](https://github.com/user-attachments/files/16960950/candle12_nomini_norbfix.log)

**Comment by elastic-rock** [comment]
Does it work now with `1.7.0`?

**Comment by licaon-kter** [comment]
You released it 10 mins ago... give it time to test :)

**Comment by licaon-kter** [comment]
Fine now: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16285
