### ISSUE TITLE
Back and front light

### ISSUE THREAD

**Issue by trudnorx** [elastic-rock/Candle#18]
There should be an option to auto turn on Android's flashlight while the app is focused and off when not. This would allow light to come both from the front and back of the device, which I find useful.

**Comment by elastic-rock** [comment]
I do not think this feature is usefull. The purpose of Candle is to act as a torch that does not shine as much, to which your feature request is in completely in opposition. If you really want to, you can always enable the flashlight using the QS tile provided on most Android phones.
