### ISSUE TITLE
Show a message in the screen while warm light is widespread

### ISSUE THREAD

**Issue by serrq** [elastic-rock/Candle#2]
Use's cases

A message for a partner while one is in the kitchen to make coffee, and its partner is yet in the bed (phone is in the bedroom).

"Good morning darling, your coffee will come soon".

With some icons? Like coffee, heart, etc.

Let me know if you like this idea.

**Comment by elastic-rock** [comment]
I have not imagined such a use case for the app. Right now, I am not really persuaded but I am leaving the floor open for discussion.

**Comment by elastic-rock** [comment]
I have decided that the app's purpose is going to be that of a flashlight/candle and thus this will not be worked on.
