### ISSUE TITLE
Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [elastic-rock/Candle#4]
Please add direct cryptocurrency addresses within the app. Easy tap and donate without leaving the app: I don't want going around to websites. I don't want support FIAT economy.

TRX, AVAX, LTC, BTC, XEC, BNB, SOL, BCH, ALGO, XTZ, DASH, FTM, XMR addresses available for donations (addresses have to be copyable).

Following an example from other developers.

![1000092943](https://github.com/cypherstack/stack_wallet/assets/113377431/44b05c36-ec6d-42db-b055-69272ccd4c63)

**Comment by elastic-rock** [comment]
I am glad to hear that my project interests you and that you want to support it. However, I am not planning on accepting donations for the moment as I primarily develop for myself. I publish them to allow others to use them if they find them useful and learn in the process.
