### ISSUE TITLE
Dynamic lights: flickering flame of a candle

### ISSUE THREAD

**Issue by serrq** [elastic-rock/Candle#5]
I imagine a candel light that flickering in the darkness.

The light move itself like the real candle. This introduce the "scenarios".

Possible scenarios:

• sunrise
• candle
• sunset
• rainy days etc.

What do you think about it?

**Comment by elastic-rock** [comment]
I like the idea with the candle. Does sunrise mean getting from a warmer colour to a less warm one (along with a change in brightness) and sunset the opposite?

**Comment by elastic-rock** [comment]
I added the candle as a new year's gimmick but the other scenarios will not be worked on
