### ISSUE TITLE
Flashes white on orientation change with custom color

### ISSUE THREAD

**Issue by Naomitr0n** [elastic-rock/Candle#8]
I have the custom color set to red since it's way easier on the eyes. Problem is, any time I accidentally rotate my phone as I'm trying to find something at night, I get a brief rather blinding flash of white.

Expected behavior: the screen should retain custom color on rotation changes without interruption.

If this isn't achievable due to some Android limitation, I imagine changing the default layout color from white to black would mean these brief flashes of white would become brief interruptions in illumination, which is _much_ preferred.

**Comment by elastic-rock** [comment]
Thank you for pointing out the issue. I will work to fix it as soon as I have some spare time.
