### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by trudnorx** [elastic-rock/Candle#9]
Great app. I would find it helpful if you could set up a default timer in the options.

E.g. maximum time -> 5 mins.

After the time is over, it either:
a) closes the app, returns to home screen, locks screen immediately, and turns screen off
or b) closes the app, returns to home screen
or c) app stays open, but screen becomes locked and turned off.
(Implement any of them, this doesn't need to be displayed as an option, I would prefer A).

The next time you open the app, it re-enables the max time you selected (e.g. 5 mins), it stays as a default.

I find this feature is justified because the app is preventing the normal screen lock mechanism and keeping the screen on indefinitely. While this will be fine for some users, for others (e.g. me) it will create problems.

In my personal case, I often need to use the app in a situation where I cannot return to my phone to close the app until a much longer time passes than it needed to stay open (so a lot of battery is wasted pointlessly).

So, I think the feature would be pretty helpful.

**Comment by elastic-rock** [comment]
I think a timer is superfluous but I will add a toggle to turn off the feature preventing the screen from turning off (meaning it will follow the system screen timeout).

**Comment by elastic-rock** [comment]
The feature has been programed and will be added in a future update (I still need to do some work for 3 button navigation).

**Comment by trudnorx** [comment]
> The feature has been programed and will be added in a future update (I still need to do some work for 3 button navigation).

Thanks
